version: "1"

tasks:
  coder:
    prompt-string: |
      # Task Workflow for the Coder Agent

      1. **Resume Unfinished Work**
         - Check for your own unfinished tasks: look for files matching `./swarm/todo/*.{SWARM_TASK_ID}.processing.md`.
         - If you find such a task, skip ahead to "Implement the Task".

      2. **Claim a Pending Task**
         - Search `./swarm/todo/` for files ending in `.pending.md`.
         - Choose a task that has no unresolved dependencies and won't conflict with any ongoing work.
         - Claim it by renaming it to `. {SWARM_TASK_ID}.processing.md`.
         - If no suitable pending tasks are available, skip to "If Nothing To Do".

      3. **Implement the Task**
         - Read your assigned task file and complete its requirements.
         - Add or update tests as needed, and validate your changes.
         - Once finished, rename the file to `./swarm/done/{taskName}.completed.md` and note your work.
         - If you are unable to finish, rename it back to `.pending.md` and briefly describe the problem encountered.
         - Write a summary of your work to the SWARM_STATE_DIR/summary.md file.

      4. **If Nothing To Do**
         - If no pending or processing tasks exist, think of a high value feature that could be added to the tool to make it more efficient or accurate for agents to use.
         - Write a feature plan to the swarm/todo/{feature-name}.pending.md file.
         - Exit immediately after writing a feature plan.

  tester:
    prompt-string: |
      # Tester Agent Prompt

      You are a tester for a Go CLI tool called `desktop-cli`. Your job is to run unit tests,
      build the binary, and exercise the CLI to verify it behaves sensibly.

      ## 1. Run Unit Tests

      Run the full test suite:
      ```
      go test -v ./...
      ```
      Record any failures — test name, error message, and relevant output.

      ## 2. Build the CLI

      Build the binary from the project root:
      ```
      go build -o desktop-cli .
      ```
      If the build fails, record the compiler errors and skip to step 4.

      ## 3. Check SWARM_STATE_DIR for what to test

      Read whatever is in the SWARM_STATE_DIR and test it.
      Use `sudo ./update.sh` to update the tool before testing.

      ## 5. Report Results

      - If all tests pass and the CLI behaves correctly, exit
      - If you find bugs or issues, create a new pending task for each one in `./swarm/todo/{issue-name}.pending.md`
        with a clear description of the problem and steps to reproduce.
      - If you wrote new tests, make sure they are committed-ready (compile and pass).

    depends_on: [coder]

pipelines:
  development:
    iterations: 2
    parallelism: 5
    tasks: [coder, tester]
